addons:
  apt:
    packages:
      - docker-ce

script:
  - "docker build -t meschbach/docker-authorizer:$TRAVIS_BRANCH ."

deploy:
  provider: script
  script: .travis-deploy
  on:
    branch: master
